### ISSUE TITLE
HTML preview cannot render the Mathjax correctly

### ISSUE THREAD

**Issue by braindevices** [wereturtle/ghostwriter#576]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
 - Ubuntu 20.04
 - Gnome

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 1.8.0
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: apt from official repo

**Describe the bug**
HTML preview cannot render the Mathjax correctly.
**To Reproduce**
1. write following:
```
The following is an equation for Pandoc:

$$
\Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,.
$$
```
2. choose settings->preview options->pandoc, the rendered result is wrong:
![Screenshot from 2021-03-23 23-15-11](https://user-images.githubusercontent.com/7507440/112225849-b3081380-8c2d-11eb-8294-eac42826277d.png)
3. choose export to pandoc html, the result is ok:
![Screenshot from 2021-03-23 23-17-25](https://user-images.githubusercontent.com/7507440/112226073-fcf0f980-8c2d-11eb-9b3d-0f3de6b0ec06.png)

**Expected behavior**
live preview window should show correct rendering result as the exported html file.

**Comment by wereturtle** [comment]
This issue is fixed in the release candidate for version 2.0.0.  Try adding the PPA for unstable releases per the README file, and you should see beautiful equations again!  :smiley:

**Comment by braindevices** [comment]
@wereturtle I tried 2.0.0. Thanks a lot for the beautiful work! Unfortunately the bug is not fixed in v2.0.0-rc5. But it is not really usable, it is keep crashing with SEGV.

Between the crashes I can see the problem remain the same when select preview as Pandoc:

![Screenshot from 2021-03-24 08-23-51](https://user-images.githubusercontent.com/7507440/112271639-79f69000-8c7b-11eb-8ef0-4f68adeb16d8.png)

The other preview mode has other problem, notice the `,` at the end:
![Screenshot from 2021-03-24 08-23-35](https://user-images.githubusercontent.com/7507440/112271703-8b3f9c80-8c7b-11eb-9d25-51c33f38b5dd.png)

Some of them are ok:

![Screenshot from 2021-03-24 08-24-08](https://user-images.githubusercontent.com/7507440/112271619-7400af00-8c7b-11eb-9c0b-6f96babfb529.png)

![Screenshot from 2021-03-24 08-24-21](https://user-images.githubusercontent.com/7507440/112271592-6b0fdd80-8c7b-11eb-830f-b1d233de1de5.png)
